### ISSUE TITLE
Error in NLParser

### ISSUE THREAD

**Issue by keshavprashantdeshpande** [DukeNLIDB/NLIDB#5]
While running the program following error occured
java.io.FileNotFoundException: edu\stanford\nlp\models\pos-tagger\english-left3words\english-left3words-distsim.tagger (The system cannot find the path specified)
![error](https://cloud.githubusercontent.com/assets/13033056/25156379/b9a1a0e4-24b7-11e7-9418-e69eb1e8e1f2.PNG)

**Comment by kepingwang** [comment]
Are you using Maven? If you are running this in eclipse, right click the project to convert to Maven project, and right click to update Maven project.

**Comment by keshavprashantdeshpande** [comment]
I am using Eclipse. This error is resolved. Now I am getting an error "Exception in Application start method".
I have tried using try and catch block in the start method of userview but there are no details of the error.

**Comment by kepingwang** [comment]
hmm... I don't quite know how to solve this given the information provided. First make sure you are using Java 8. I guess it is some problem with JavaFX. You can search the problem with the keyword JavaFX.

**Comment by keshavprashantdeshpande** [comment]
I am using Java 8 but unable to install JavaFX plug-in. Any alternate solutions?

**Comment by kepingwang** [comment]
That plug-in turns out not necessary for the project. Can you try install the newest version of eclipse 
 (Neon)?

**Comment by keshavprashantdeshpande** [comment]
Same error with Neon also.

**Comment by keshavprashantdeshpande** [comment]
If I change the GUI what are the steps I will need to follow? Can you guide me through this?

**Comment by kepingwang** [comment]
You can have a look at `app.Controller` and `ui.UserView`, where you may find the procedure of our program. Also you can refer to our final report. The classes inside the `model` package are (probably) independent of the JavaFX GUI.

**Comment by kepingwang** [comment]
I'll soon be working on making it a web service (instead of a stupid JavaFX app).
